server:
  port: 8706
  forward-headers-strategy: framework
  servlet:
    context_path: /discount/api/v1
  error:
    include-message: always
    include-exception: false
    include-binding-errors: never
    include-stacktrace: never

spring:
  application:
    name: discount-api-service
  datasource:
    url: jdbc:mysql://localhost:3306/discount_db
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: info